# docker-compose.yml

version: '3.8'

services:
  auth-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  auth-server:
    build:
      context: .
      dockerfile: ./apps/auth-server/Dockerfile
    restart: always
    env_file:
      - ./apps/auth-server/.env.docker
    ports:
      - '3001:3001'
    depends_on:
      - auth-db

  resource-server:
    build:
      context: .
      dockerfile: ./apps/resource-server/Dockerfile
    restart: always
    env_file:
      - ./apps/resource-server/.env.docker
    ports:
      - '4001:4001'

volumes:
  postgres-data:
    driver: local
